version: '3'

services:

  ledger-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000-8004"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    env_file:
      - .env.local
    depends_on:
      - postgres
    networks:
      - backend


  database:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env.local
    restart: always
    networks:
      - backend

  redis:
    image: redis:alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    env_file:
      - .env.local
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - 'redis_data:/data'
    networks:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - ledger-service
    ports:
      - "4000:4000"
    networks:
      - backend

  e2e-tests:
    build:
      context: .
      dockerfile: e2e/Dockerfile.test
    depends_on:
      - ledger-service
    env_file:
      - .env.local
    networks:
      - backend
    entrypoint: [ "./e2e/wait-for-services.sh", "go", "test", "-v", "-parallel", "4", "./e2e" ]

volumes:
  postgres_data:
  redis_data:
    driver: local
  nginx_logs:
    driver: local
networks:
  backend:
    driver: bridge
